/**
 * Route constants — single source of truth for all path strings.
 * Import and reference by name instead of using string literals.
 */
export const ROUTES = {
  HOME: "/",
  SIGNUP: "/signup",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  VERIFY_CODE: "/verify-code",
  RESET_PASSWORD: "/reset-password",
  PRODUCTS: "/products",
  PRODUCT_DETAIL_BUY: "/product-detail-buy",
  PRODUCT_DETAIL_SELL: "/product-detail-sell",
  SELLER_PROFILE: "/seller-profile",
  SELLER_REVIEWS: "/seller-reviews",
  PROFILE: "/profile",
  FOLLOWERS: "/followers",
  FOLLOWINGS: "/followings",
  SETTINGS_PROFILE: "/settings-profile",
  SETTINGS_PAYMENTS: "/settings-payments",
  SETTINGS_SELLING: "/settings-selling",
  SETTINGS_NOTIFICATIONS: "/settings-notifications",
  SETTINGS_ACCOUNT: "/settings-account",
  ADD_PAYMENT_CARD: "/add-payment-card",
  ADD_WITHDRAWAL_METHOD: "/add-withdrawal-method",
  CHANGE_PASSWORD: "/change-password",
  WALLET: "/wallet",
  CHECKOUT_DELIVERY: "/checkout-delivery",
  CHECKOUT_COLLECTION: "/checkout-collection",
  ORDER_CONFIRMATION: "/order-confirmation",
  MY_PURCHASES: "/my-purchases",
  MY_SALES: "/my-sales",
  TRACK_ORDER: "/track-order",
  DISPUTE: "/dispute",
  DISPUTE_STATUS: "/dispute-status",
  SELL_ITEM: "/sell-item",
  EDIT_ITEM: "/edit-item",
  CREATE_BUNDLE: "/create-bundle",
  LEAVE_REVIEW: "/leave-review",
  SAVED_ITEMS: "/saved-items",
  MESSAGES: "/messages",
  OFFER_SENT_PENDING: "/offer-sent-pending",
  OFFER_SENT_CANCELLED: "/offer-sent-cancelled",
  OFFER_SENT_COUNTER: "/offer-sent-counter",
  OFFER_SENT_ACCEPTED: "/offer-sent-accepted",
  OFFER_RECEIVED_PENDING: "/offer-received-pending",
  OFFER_RECEIVED_COUNTER: "/offer-received-counter",
  OFFER_RECEIVED_ACCEPTED: "/offer-received-accepted",
  NOTIFICATIONS: "/notifications",
  ABOUT: "/about",
  HOW_IT_WORKS: "/how-it-works",
  BUYER_PROTECTION: "/buyer-protection",
  HELP_CENTRE: "/help-centre",
  TERMS: "/terms",
  PRIVACY: "/privacy",
} as const;

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES];
