import { ROUTES } from "@/routes";

export const screens = [
  { path: ROUTES.HOME, label: "Home Page" },
  { path: ROUTES.SIGNUP, label: "Sign Up" },
  { path: ROUTES.LOGIN, label: "Log In" },
  { path: ROUTES.FORGOT_PASSWORD, label: "Forgot Password" },
  { path: ROUTES.VERIFY_CODE, label: "Verify Code" },
  { path: ROUTES.RESET_PASSWORD, label: "Reset Password" },
  { path: ROUTES.PRODUCTS, label: "Products Listing" },
  { path: ROUTES.PRODUCT_DETAIL_BUY, label: "Product Detail (Buy)" },
  { path: ROUTES.PRODUCT_DETAIL_SELL, label: "Product Detail (Sell)" },
  { path: ROUTES.PROFILE, label: "My Profile" },
  { path: ROUTES.FOLLOWERS, label: "Followers" },
  { path: ROUTES.FOLLOWINGS, label: "Followings" },
  { path: ROUTES.NOTIFICATIONS, label: "Notifications" },
  { path: ROUTES.SAVED_ITEMS, label: "Saved Items" },
  { path: ROUTES.WALLET, label: "Wallet" },
  { path: ROUTES.SELLER_PROFILE, label: "Seller Profile" },
  { path: ROUTES.SELLER_REVIEWS, label: "Seller Reviews" },
  { path: ROUTES.SELL_ITEM, label: "Sell an Item" },
  { path: ROUTES.EDIT_ITEM, label: "Edit Item" },
  { path: ROUTES.CREATE_BUNDLE, label: "Create Bundle" },
  { path: ROUTES.CHECKOUT_DELIVERY, label: "Checkout (Delivery)" },
  { path: ROUTES.CHECKOUT_COLLECTION, label: "Checkout (Collection)" },
  { path: ROUTES.ORDER_CONFIRMATION, label: "Order Confirmation" },
  { path: ROUTES.MY_PURCHASES, label: "My Purchases" },
  { path: ROUTES.MY_SALES, label: "My Sales" },
  { path: ROUTES.TRACK_ORDER, label: "Track Order" },
  { path: ROUTES.LEAVE_REVIEW, label: "Leave a Review" },
  { path: ROUTES.DISPUTE, label: "Dispute Request" },
  { path: ROUTES.DISPUTE_STATUS, label: "Dispute Status" },
  { path: ROUTES.SETTINGS_PROFILE, label: "Settings (Profile Details)" },
  { path: ROUTES.SETTINGS_PAYMENTS, label: "Settings (Payments)" },
  { path: ROUTES.SETTINGS_SELLING, label: "Settings (Selling)" },
  { path: ROUTES.SETTINGS_NOTIFICATIONS, label: "Settings (Notifications)" },
  { path: ROUTES.SETTINGS_ACCOUNT, label: "Settings (Account)" },
  { path: ROUTES.ADD_PAYMENT_CARD, label: "Add Payment Card" },
  { path: ROUTES.ADD_WITHDRAWAL_METHOD, label: "Add Withdrawal Method" },
  { path: ROUTES.CHANGE_PASSWORD, label: "Change Password" },
  { path: ROUTES.MESSAGES, label: "Messages" },
  { path: ROUTES.OFFER_SENT_PENDING, label: "Offer Sent (Pending)" },
  { path: ROUTES.OFFER_SENT_CANCELLED, label: "Offer Sent (Cancelled)" },
  { path: ROUTES.OFFER_SENT_COUNTER, label: "Offer Sent (Counter)" },
  { path: ROUTES.OFFER_SENT_ACCEPTED, label: "Offer Sent (Accepted)" },
  { path: ROUTES.OFFER_RECEIVED_PENDING, label: "Offer Received (Pending)" },
  { path: ROUTES.OFFER_RECEIVED_COUNTER, label: "Offer Received (Counter)" },
  { path: ROUTES.OFFER_RECEIVED_ACCEPTED, label: "Offer Received (Accepted)" },
  { path: ROUTES.ABOUT, label: "About Us" },
  { path: ROUTES.HOW_IT_WORKS, label: "How It Works" },
  { path: ROUTES.BUYER_PROTECTION, label: "Buyer Protection" },
  { path: ROUTES.HELP_CENTRE, label: "Help Centre" },
  { path: ROUTES.TERMS, label: "Terms & Conditions" },
  { path: ROUTES.PRIVACY, label: "Privacy Policy" },
];
